name: Build

on:
  push:
    branches: [ master, hotfix/*, feature/*, bugfix/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.json') }}
      - name: Build
        run: make build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblockTests.dll
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblocks.ini
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblocks.pdb