name: Build

on:
  push:
    branches: [ master, hotfix/*, feature/*, bugfix/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: make build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblockTests.dll
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblocks.ini
            AutomaticRoadblockTests\bin\x64\Debug\AutomaticRoadblocks.pdb