name: Build

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.json') }}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            5.0.x
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            AutomaticRoadblock/bin/x64/Debug/AutomaticRoadblocks.dll
            AutomaticRoadblock/bin/x64/Debug/AutomaticRoadblocks.ini
            AutomaticRoadblock/bin/x64/Debug/AutomaticRoadblocks.pdb