name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: The release type
        options:
          - release
          - release-bugfix
    
jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: NuGet Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore AutomaticRoadblock.sln
      - name: Build
        run: make ${{ inputs.choice }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            Build/