name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: The release type
        options:
          - release
          - release-bugfix
    
jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            5.0.x
      - name: Install dependencies
        run: make restore
      - name: Test
        run: make test
      - name: Build
        run: make ${{ inputs.choice }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            Build/