name: Release

on:
  workflow_dispatch:
    inputs: {}
    
jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: make release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            AutomaticRoadblockTests\bin\x64\Release\AutomaticRoadblockTests.dll
            AutomaticRoadblockTests\bin\x64\Release\AutomaticRoadblocks.ini
            AutomaticRoadblockTests\bin\x64\Release\AutomaticRoadblocks.pdb